FROM node:22-alpine

RUN apk add --no-cache bash libc6-compat curl
RUN npm install -g @angular/cli @ionic/cli @ionic/storage-angular

USER node
WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

EXPOSE 8100 4200

CMD ["ionic", "serve", "--host", "0.0.0.0", "--port", "8100", "--poll=3000"]
