FROM node:23-alpine

RUN apk add --no-cache bash libc6-compat curl
RUN npm install -g @angular/cli @ionic/cli
RUN adduser -D appuser
WORKDIR /usr/src/app
COPY . .
RUN chown -R appuser:appuser /usr/src/app
USER appuser

EXPOSE 8100 4200

ENTRYPOINT ["sh", "-c", "chown -R appuser:appuser /usr/src/app && ionic serve --host 0.0.0.0 --port 8100"]
