    FROM python:3.13

    WORKDIR /usr/src/backend

    RUN apt-get update && apt-get install --no-install-recommends netcat-openbsd && rm -rf /var/lib/apt/lists/*

    COPY requirements.txt .

    RUN pip install --no-cache-dir -r requirements.txt

    COPY . .

    ENV FLASK_APP=app/run.py
    ENV FLASK_ENV=development

    EXPOSE 5000

    ENTRYPOINT [ "./entrypoint.sh" ]


