FROM python:alpine3.20

WORKDIR /usr/src/app

RUN apk update && apk add --no-cache netcat-openbsd

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x ./entrypoint.sh

ENV FLASK_APP=app/run.py
ENV FLASK_ENV=development

EXPOSE 5000

ENTRYPOINT [ "./entrypoint.sh" ]